frase = '  aula de python    '
print(frase)
print(frase[3])
print(frase[2:13])
print(frase[:13])
print(frase[4:])
print(frase[1:13:2])
print(frase[::2])
print(frase.count('a'))
print(frase.find('n'))
print(frase.join('d'))
print(len(frase))
print(frase.upper())
print(frase.strip())
print(frase.replace('python', 'android'))
print('aula' in frase)
print(frase.split())
dividido = frase.split()
print(dividido[0])

